version: '3'
services:
    
    db:
        container_name: mysql-app
        build: ./build/mysql/
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: localhost
            MYSQL_USER: localadmin
            MYSQL_PASSWORD: localadmin
            MYSQL_DATABASE: tb_app_local
        ports: 
            - "3066:3066"
        volumes: 
            - ./volumes/mysql:/var/lib/mysql
    
    php-fpm:
        container_name: php-fpm
        build: ./build/php/
        restart: always
        depends_on: 
            - db
        ports: 
            - "9000:9000"
        #volumes: 
            
    web-app:
        container_name: nginx-app
        build: ./build/nginx/
        restart: always
        depends_on: 
            - php-fpm
        ports: 
            - "443:443"
            - "80:80"
        volumes:
            - ./volumes/config/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./volumes/config/nginx/config/app.local:/etc/nginx/sites-available/app.local:ro
            - ./volumes/config/nginx/private/ssl/app.local.crt:/etc/nginx/ssl/app.local.crt:ro
            - ./volumes/config/nginx/private/ssl/app.local.crt:/etc/nginx/ssl/app.local.key:ro
            - ./volumes/config/nginx/www/public/:/home/www/public/

networks:
    vnet-webApp-local:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/24

        