workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      groups:
        - ENV_AGFARMUS 
      #   - appstore_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY) - https://docs.codemagic.io/code-signing-yaml/signing-ios/
      #   - certificate_credentials # <-- (Includes CERTIFICATE_PRIVATE_KEY)
      #   - other # <-- (Includes APP_STORE_APP_ID - Put the app id number here. This is found in App Store Connect > App > General > App Information)
      # # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      # vars:
      #   XCODE_WORKSPACE: "agroapp.xcworkspace" # <-- Put the name of your Xcode workspace here
      #   XCODE_SCHEME: "agroapp.xcscheme" # <-- Put the name of your Xcode scheme here        
      #   BUNDLE_ID: "com.agfarmus.test" # <-- Put your Bundle Id here e.g com.domain.myapp
      #   APP_STORE_CONNECT_ISSUER_ID: "e1f7e544-ec9c-432e-9a15-32a6ead6ad32"
      #   APP_STORE_CONNECT_KEY_IDENTIFIER: "335G6GP645"
      #   APP_STORE_CONNECT_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----IGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpFpZBaOpX3/ahqslGufs+AGtw6oIfa3lZOcWPDN0JDSgCgYIKoZIzj0DAQehRANCAARQQTtgR1V8ZAjQ1KXcuQwXWDzkQxEzbEterQ70LeHagEJFub1XNuchj5JRHfAKlCDAnSg5xtFT9zBY9DJy1A7b\n-----END PRIVATE KEY-----"
      #   CERTIFICATE_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAoQ+CqSmztT58X1E8lc6AE+rcd3adShPXO90EP7rrb5WWeeyNAzWTCoKQZp0YLu+tl3wWb1kmZ68hr8wJ/ySYW9nbGC2Nf2HxmAnbpCHyequ3HC1neDh41X5KvbB9oWw5B0uTe0OcDbkrdc6lLzvebqLxDDv/ymByK0aZkIPd3Wiii07EufVquuQ0WuySclobN56XUcrdEbBUe1aUvu+/wuaLJFr+XqPqGDg79J04eyvdpzVD8Er+ryjKr0bs30wi0J1uXRNCxRg38eT/7OgBDtl8c4Jz6gjU7FBEmBjeTQIRAu3Jb0nHLkUM75LgL1Rcx5/7+AV2+bZfTFf2WLmmgQIDAQABAoIBAQCQteLsIy/4dQBClDcfUr75JliYbda9LD6C5v5eVJAdXgYp3kSE0aogE1ezGwsTgP4z0aZGvY8oMc7OqUGCIVtTi9azTpqIDXSI6rKSMn4vggGwK4uAFR1clXCKJv16AEbtKxaD9idMnUdTPixk2CHuvjBekbouF6H9CB4KHrFFsMTmb2ZtiD/K0ge3JNp/iX10uFTxEgBTIwE2wwbM5FJQaLajsv9YYP9N6abdP1PDomq+5lNzj0sk5XFnFvDZGYaD2NUPmwDWV8BKX5HrWWmAVtrZm64P1F5pd5RYjw+AZfvoCiz8w1bNpT4/nwINtD1pLZbmMsPjqS9d0+bQ/0NRAoGBANG3IwFfRQ1t05L/5NeYDNffXbUYaiR7+v5tVz8xHHsw1Teg5/cGVeeCO+1qF7/Vr9oqeD2WCkvBz1TL+QRncM8y0C3qedd1miXf0xhDkCZ0CRPYmoMPLKrcPJf8yJNLLQKgfExnFdv3ovpWV6XI8C4AIrmlTQPMwWaaEagyryBTAoGBAMSbZBGNt6C1jeXQvdCSQSwwWk0CwpG2gk/fneziGgOq3sb7aqsO6rs0RC1C3VJgEiq/mUcj07zxaouE1vW8lu7Vrddbc+ghhx6QmeCE06r7pAhU1IjvBaFIEHvld7vI0isI4Ahvle5xld2AtLDbv0+SJAevPwFvBG9+G4FgQRNbAoGAJttm+gcb9UwHKrKNRUEgCBOT+k0GxbHPJLs/si64Vz8KEp+Wu1eKLTYdQnUo51uBlMvPsaGOUNEdSFnuztkXttx0ZD2Qy9I3eJMLOvCx0d4oHGxC3Mu/+/yIoaStyVThhx4TSdjD3Rj6MqYy4T3k+rD9viYZqf2TTB557Q9PEY8CgYAELc1dtiZuCw3eEabHNSSffNOeiW17TWbNrdIcg93LsCkWD6f/xMxmeEDuuVoc8x/PuszWP0Oz42nBV2x+QqjuoKoWRsJa78OAedBbfldFbh3Zc3wlAPecqvx2tbTqz+TvtzuT0lNcgxuNXrv4emNBnLiZVTdAn4x3ljWddV9MuwKBgErruE4zAuR6W80WOI1hg1DFRPwsCTCYpCBDUAtXBf/5h7JL3j0CgUsZMcuJpKVup+PyPnsyXEtef8NHLJaPfFGYPedIWi5hZUE+9sjmA9YgD6mCJy6jiHquk9nTYMP2XwJpV0XgC0VM40bHbY4xNfPM1r/NTLjwDQvhzY3ROxSx-----END RSA PRIVATE KEY-----"
      node: 14
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: feature/agfarmus-70
          include: true
          source: true
    scripts:
      # - name: gerando certificados
      #   script: |
      #               ssh-keygen -t rsa -b 2048 -m PEM -f ~/Desktop/codemagic_private_key -q -N ""
      - name: Install npm dependencies
        script: |
                    yarn install
      - name: Install CocoaPods dependencies
        script: |
                    cd ios && pod install
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
      - name: App-store-connect
        script: |
          # For information about Codemagic CLI  visit: https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/README.md
          # For details about the --type paramater below - https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/fetch-signing-files.md#--typeios_app_adhoc--ios_app_development--ios_app_inhouse--ios_app_store--mac_app_development--mac_app_direct--mac_app_store--mac_catalyst_app_development--mac_catalyst_app_direct--mac_catalyst_app_store--tvos_app_adhoc--tvos_app_development--tvos_app_inhouse--tvos_app_store
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create --verbose     
      - name: Use system default keychain
        script: |
                    keychain add-certificates
      - name: Increment build number
        script: |
          #!/bin/sh
          set -e
          set -x
          cd $FCI_BUILD_DIR/ios
          # agvtool new-version -all $(($BUILD_NUMBER + 1))
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))          
      - name: Set up code signing settings on Xcode project
        script: |
                    xcode-project use-profiles --warn-only
      - name: Build ipa for distribution
        script: |
                    xcode-project build-ipa --workspace "ios/agroapp.xcworkspace" --scheme "agroapp"
                    # xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" 
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true     # To not receive a notification when a build succeeds
          failure: false    # To not receive a notification when a build fails
      # slack:
      #   # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
      #   channel: '#channel-name'
      #   notify_on_build_start: true   # To receive a notification when a build starts
      #   notify:
      #     success: true               # To receive a notification when a build succeeds
      #     failure: false              # To not receive a notification when a build fails
      app_store_connect:
          api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID       # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
          submit_to_testflight: true        # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.  